version: "3"

services:
  db:
    container_name: baespotnuxt_db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data

  backend:
    container_name: baespotnuxt_backend
    build: backend/
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - 3000:3000

  frontend:
    container_name: baespotnuxt_frontend
    build: frontend/
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - 8080:3000